services:
  postgres:
    image: postgres:16
    container_name: ridfix-postgres
    environment:
      POSTGRES_DB: ridfix_db
      POSTGRES_USER: ridfix_user
      POSTGRES_PASSWORD: Allahou99!
    ports:
      - "5432:5432"
    volumes:
      - ridfix_pgdata:/var/lib/postgresql/data
volumes:
  ridfix_pgdata:
